### ISSUE TITLE
Published azure-storage-blob 2.0.2 still requires Nokogiri 1.11.0.rc2

### ISSUE THREAD

**Issue by grncdr** [Azure/azure-storage-ruby#205]
I've seen there were PRs merged to fix this but the actual published gem (downloaded from Rubygems.org) contains the folllowing metadata that makes the Gem incompatible with Nokogiri 1.12:

```yaml
- !ruby/object:Gem::Dependency
  name: nokogiri
  requirement: !ruby/object:Gem::Requirement
    requirements:
    - - "~>"
      - !ruby/object:Gem::Version
        version: 1.11.0.rc2
```

I am not super familiar with Rubygem tooling but it appears that the Ruby version used to package the gem is determining the Nokogiri dependency that is "baked in" to the final zip file.

As a a workaround, installing from source will work because the Gemspec is evaluated using the local Ruby version.

```
git 'https://github.com/Azure/azure-storage-ruby.git' do
  gem 'azure-storage-blob'
end
```
